server:
  port: 9000
spring:
  datasource:
      url: jdbc:mariadb://localhost:3307/auth_tutorial?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password: 1234
      driver-class-name: org.mariadb.jdbc.Driver
#  thymeleaf:
#      cache: false
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update